name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -e . -r requirements-dev.txt
      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: ${{ runner.os }}-precommit-
      - run: pre-commit run --all-files --show-diff-on-failure
      - run: pip-audit -r requirements.txt --format columns
      - name: Snyk scan
        if: ${{ secrets.SNYK_TOKEN != '' }}
        uses: snyk/actions/python@0.4.0
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - run: pytest --cov=. --cov-report=term-missing --cov-report=xml --cov-fail-under=80
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
      - name: Upload Railway logs
        run: |
          if command -v railway >/dev/null; then
            railway logs --follow --detach > logs/latest_railway.log &
            sleep 5
            pkill -f "railway logs" || true
            cat logs/latest_railway.log
          fi
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: railway-logs
          path: logs/latest_railway.log
